package raster

// More resvg comparisons, appended to featureSynths (see features_test.go).

var extraSynths = []synth{
	{"x-filter-text", svgHead + `<defs><filter id="f"><feGaussianBlur stdDeviation="1.5"/></filter></defs><text x="10" y="50" font-family="sans-serif" font-size="30" fill="navy" filter="url(#f)">Blur</text></svg>`, 0.1, 0.25},
	{"x-filter-image-use", svgHead + `<defs><filter id="f"><feOffset dx="5" dy="5"/></filter><image id="i" width="30" height="30" href="data:image/png;base64,` + tinyPNG + `"/></defs><use href="#i" x="10" y="10" filter="url(#f)"/><g filter="url(#f)"><image x="60" y="10" width="30" height="30" href="data:image/png;base64,` + tinyPNG + `"/></g></svg>`, 3.77, 3.74},
	{"x-filter-nested-svg", svgHead + `<defs><filter id="f"><feGaussianBlur stdDeviation="2"/></filter></defs><svg x="10" y="10" width="60" height="60" viewBox="0 0 30 30" filter="url(#f)"><rect width="20" height="20" fill="red"/></svg></svg>`, 2.36, 7.42},
	{"x-mask-gradient-group", svgHead + `<defs><linearGradient id="g" x1="0" x2="1"><stop offset="0" stop-color="#000"/><stop offset="1" stop-color="#fff"/></linearGradient><mask id="m" maskContentUnits="objectBoundingBox"><rect width="1" height="1" fill="url(#g)"/></mask></defs>
<g mask="url(#m)"><rect x="10" y="10" width="40" height="80" fill="blue"/><rect x="50" y="10" width="60" height="80" fill="green"/></g></svg>`, 0.1, 0.25},
	{"x-pattern-text", svgHead + `<defs><pattern id="p" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="3" height="3" fill="red"/><rect x="3" y="3" width="3" height="3" fill="blue"/></pattern></defs><text x="5" y="60" font-family="sans-serif" font-size="50" font-weight="bold" fill="url(#p)">Ab</text></svg>`, 0.1, 0.25},
	{"x-marker-circle", svgHead + `<defs><marker id="m" markerWidth="4" markerHeight="4" refX="2" refY="2" orient="0.5rad"><path d="M0 2 L4 2" stroke="red"/></marker></defs><circle cx="50" cy="50" r="30" fill="none" stroke="black" marker-start="url(#m)" marker-mid="url(#m)" marker-end="url(#m)"/></svg>`, 0.21, 1.43},
	{"x-marker-viewbox-none", svgHead + `<defs><marker id="m" markerWidth="10" markerHeight="5" viewBox="0 0 4 4" preserveAspectRatio="none" refX="2" refY="2" orient="auto"><path d="M0 0 L4 2 L0 4z" fill="green"/></marker></defs><path d="M10 20 Q 60 -10 110 20 T 110 70" fill="none" stroke="black" marker-end="url(#m)" marker-mid="url(#m)"/></svg>`, 0.27, 2.07},
	{"x-css-inherit", svgHead + `<style>g { fill: teal; stroke: black } .r { fill: inherit; stroke: none }</style><g><rect class="r" width="40" height="40"/><rect x="50" width="40" height="40" style="stroke-width:5"/></g></svg>`, 0.1, 0.25},
	{"x-deco-tspan", svgHead + `<text x="10" y="30" font-family="sans-serif" font-size="16" text-decoration="underline">Under <tspan dx="6" fill="red">line</tspan> end</text><text x="10" y="60" font-family="sans-serif" font-size="16" letter-spacing="3" text-decoration="line-through">Spaced out</text><text x="60" y="90" text-anchor="middle" font-family="serif" font-size="16" text-decoration="overline">Middle</text></svg>`, 0.43, 1.2},
	{"x-textlength-anchor", svgHead + `<text x="60" y="30" text-anchor="middle" textLength="80" font-family="sans-serif" font-size="14">Centered</text><text x="60" y="60" text-anchor="middle" textLength="80" lengthAdjust="spacingAndGlyphs" font-family="sans-serif" font-size="14">Centered</text><text x="10" y="90" font-family="sans-serif" font-size="12">a<tspan textLength="60">bcdef</tspan>gh</text></svg>`, 0.1, 0.47},
	{"x-baseline", svgHead + `<line x1="0" y1="20" x2="120" y2="20" stroke="#ccc"/><text x="5" y="20" font-family="sans-serif" font-size="14" dominant-baseline="middle">Mid</text><text x="45" y="20" font-family="sans-serif" font-size="14" dominant-baseline="central">Cen</text><text x="85" y="20" font-family="sans-serif" font-size="14" dominant-baseline="hanging">Han</text>
<text x="5" y="60" font-family="serif" font-size="14" dominant-baseline="text-before-edge">Bef</text><text x="45" y="60" font-family="serif" font-size="14" dominant-baseline="text-after-edge">Aft</text><text x="85" y="60" font-family="serif" font-size="14" dominant-baseline="mathematical">Mat</text>
<text x="5" y="90" font-family="sans-serif" font-size="14">x<tspan baseline-shift="sub">sub</tspan><tspan baseline-shift="super">sup</tspan><tspan baseline-shift="5">up</tspan></text></svg>`, 0.1, 0.38},
	{"x-clip-nested-obb", svgHead + `<defs><clipPath id="a" clipPathUnits="objectBoundingBox" transform="rotate(10)"><circle cx="0.5" cy="0.5" r="0.5"/></clipPath><clipPath id="b" clip-path="url(#a)"><rect x="0" y="0" width="70" height="50"/></clipPath></defs><rect x="10" y="10" width="100" height="80" fill="purple" clip-path="url(#b)"/></svg>`, 0.1, 0.25},
	{"x-filter-opacity-blend", svgHead + `<defs><filter id="f"><feGaussianBlur stdDeviation="3"/></filter></defs><rect width="120" height="100" fill="#fd0"/><circle cx="60" cy="50" r="30" fill="blue" filter="url(#f)" opacity="0.6" style="mix-blend-mode:multiply"/></svg>`, 0.1, 0.25},
	{"x-filter-chain-two", svgHead + `<defs><filter id="a"><feOffset dx="8" dy="0"/></filter><filter id="b"><feGaussianBlur stdDeviation="3"/></filter></defs><rect x="20" y="30" width="40" height="40" fill="red" filter="url(#a) url(#b)"/></svg>`, 0.1, 0.25},
	{"x-filter-srgb-blur", svgHead + `<defs><filter id="f" color-interpolation-filters="sRGB"><feGaussianBlur stdDeviation="5"/></filter></defs><rect x="20" y="20" width="40" height="40" fill="#f80" filter="url(#f)"/><rect x="70" y="20" width="40" height="40" fill="#08f" filter="url(#f)"/></svg>`, 0.1, 0.25},
	{"x-component-transfer", svgHead + `<defs><filter id="f"><feComponentTransfer><feFuncR type="linear" slope="0.5" intercept="0.2"/><feFuncG type="table" tableValues="1 0"/><feFuncB type="discrete" tableValues="0 0.5 1"/><feFuncA type="gamma" amplitude="1" exponent="0.5" offset="0"/></feComponentTransfer></filter></defs><rect x="10" y="10" width="100" height="80" fill="url(#g)" filter="url(#f)"/><defs><linearGradient id="g"><stop offset="0" stop-color="#ff0000"/><stop offset="1" stop-color="#0000ff"/></linearGradient></defs></svg>`, 0.1, 0.25},
}

func init() { featureSynths = append(featureSynths, extraSynths...) }
