package purego_test

import (
	"flag"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/mgilbir/aster/internal/fonts/dejavu"
	"github.com/mgilbir/aster/purego"
	"github.com/mgilbir/aster/purego/internal/svgdiff"
)

var compareHarfBuzz = flag.Bool("compare.harfbuzz", false, "measure text with WithHarfBuzzTextMetrics in TestAgainstUpstreamRenderings")

// TestAgainstUpstreamRenderings compares purego with the SVGs upstream Vega
// 6.4.0 / Vega-Lite 6.4.3 render in node for the Vega-Lite examples
// (../testdata/vega-lite/v6.4.3/expected, generated by gen_expected.mjs with
// node-canvas measuring DejaVu Sans). Text widths come from different font
// engines on the two sides (node-canvas vs purego's forme shaping), so
// coordinates are compared within half a pixel. It reports a scoreboard.
func TestAgainstUpstreamRenderings(t *testing.T) {
	if testing.Short() {
		t.Skip("slow: renders the Vega-Lite example corpus")
	}
	extra := []purego.Option{}
	if *compareHarfBuzz {
		extra = append(extra, purego.WithHarfBuzzTextMetrics())
	}
	c, err := purego.New(append(extra,
		purego.WithFont("DejaVu Sans", dejavu.SansRegular), purego.WithFont("DejaVu Sans", dejavu.SansBold),
		purego.WithFont("DejaVu Sans", dejavu.SansOblique), purego.WithFont("DejaVu Sans", dejavu.SansBoldOblique),
		purego.WithFont("DejaVu Sans Mono", dejavu.MonoRegular), purego.WithFont("DejaVu Sans Mono", dejavu.MonoBold),
		purego.WithFont("DejaVu Sans Mono", dejavu.MonoOblique), purego.WithFont("DejaVu Sans Mono", dejavu.MonoBoldOblique),
		purego.WithDefaultFontFamily("DejaVu Sans"), purego.WithDefaultMonospaceFamily("DejaVu Sans Mono"),
		purego.WithLoader(corpusLoader(t)))...)
	if err != nil {
		t.Fatal(err)
	}
	defer c.Close()
	specs, _ := filepath.Glob("../testdata/vega-lite/v6.4.3/specs/*.vl.json")
	sort.Strings(specs)
	var identical, equal, errs int
	var differ []string
	for _, f := range specs {
		name := strings.TrimSuffix(filepath.Base(f), ".vl.json")
		if *compareFilter != "" && !strings.Contains(name, *compareFilter) {
			continue
		}
		want, err := os.ReadFile("../testdata/vega-lite/v6.4.3/expected/" + name + ".svg")
		if err != nil {
			continue
		}
		spec, _ := os.ReadFile(f)
		got, err := c.VegaLiteToSVG(spec)
		if err != nil {
			errs++
			t.Logf("%s: %v", name, firstLine(err.Error()))
			continue
		}
		d, err := svgdiff.Compare([]byte(got), want, svgdiff.Options{Abs: 0.5, Rel: 1e-6})
		switch {
		case err != nil:
			differ = append(differ, name+": "+err.Error())
		case d.Identical:
			identical++
		case d.Equal:
			equal++
		default:
			differ = append(differ, name+": "+d.Diff)
		}
	}
	for _, d := range differ {
		if *compareVerbose {
			t.Log(firstLine(d))
		}
	}
	t.Logf("vs upstream (node Vega 6.4.0): %d specs, %d identical, %d equal within 0.5px, %d differ, %d errors",
		identical+equal+len(differ)+errs, identical, equal, len(differ), errs)
}
