// Emits ../palettes.go: the colour tables of vega-scale's scheme registry
// (vega-scale palettes.js plus the categorical arrays it takes from
// d3-scale-chromatic).
// Run: NODE_PATH=<node_modules> node gen_palettes.mjs > ../palettes.go
import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
const require = createRequire(path.join(process.env.NODE_PATH, 'x.js'));
const chroma = await import(require.resolve('d3-scale-chromatic'));
const vsDir = path.join(process.env.NODE_PATH, 'vega-scale');
const pal = await import(path.join(vsDir, 'src/palettes.js'));

const hexOf = (arr) => arr.map((c) => c.replace('#', '')).join('');
const out = [];
out.push('// Code generated by testdata/gen_palettes.mjs; DO NOT EDIT.\n');
out.push('package scale\n');
out.push('// palettes maps scheme names to concatenated rrggbb hex triples: the discrete');
out.push('// (categorical) palettes and the ramps that vega-scale interpolates piecewise in RGB.');
const emit = (name, table) => {
  out.push(`var ${name} = []palette{`);
  for (const [k, v] of Object.entries(table)) {
    const hex = Array.isArray(v) ? hexOf(v) : v;
    out.push(`\t{"${k.toLowerCase()}", "${hex}"},`);
  }
  out.push('}\n');
};
out.push('type palette struct{ name, hex string }\n');
emit('discretePalettes', pal.discrete);
emit('continuousPalettes', pal.continuous);
process.stdout.write(out.join('\n'));
