#!/usr/bin/env bash
# Records upstream's own test suites as vectors: testdata/upstream-vectors-cache/<package>.json.
#
# 1. take the installed version of each package from testdata/oracle-node/node_modules;
# 2. shallow-clone the matching git tag of vega/vega and of each d3 repository (their tests are not
#    published to npm) into testdata/upstream-clones/;
# 3. run each package's test files against the INSTALLED package with a test-runner shim, recording
#    every call with upstream's actual answer (testdata/oracle-node/record-upstream-tests.mjs).
#
# Both output directories are git-ignored: the vectors are derived data, regenerated by this script.
# The Go replays (TestUpstream* in internal/...) skip when they are absent, and fail instead with
# ASTER_ORACLE=require, as in CI.
#
# Usage: scripts/record-upstream-vectors.sh
set -euo pipefail
cd "$(dirname "$0")/.."

ROOT="$PWD"
NODE_DIR="$ROOT/testdata/oracle-node"
OUT="$ROOT/testdata/upstream-vectors-cache"
CLONES="$ROOT/testdata/upstream-clones"

if [ ! -d "$NODE_DIR/node_modules" ]; then
  (cd "$NODE_DIR" && npm ci --silent)
fi
mkdir -p "$OUT" "$CLONES"
# One recording per run: a stale file for a package that now records nothing must not survive.
rm -f "$OUT"/*.json

VERSION="$(node -p "require('$NODE_DIR/node_modules/vega/package.json').version")"
echo "==> Vega $VERSION (from the installed package)"

clone_tag() { # <dir> <url> <tag>
  local dir="$1" url="$2" tag="$3"
  if ! { [ -d "$dir/.git" ] && [ "$(git -C "$dir" describe --tags --exact-match 2>/dev/null || true)" = "$tag" ]; }; then
    rm -rf "$dir"
    git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$tag" "$url" "$dir"
  fi
  # A test's helper modules (asserts.js, ...) import bare packages (internmap, d3-polygon): they
  # resolve from the installed ones.
  ln -sfn "$NODE_DIR/node_modules" "$dir/node_modules"
}

clone_tag "$CLONES/vega" https://github.com/vega/vega.git "v$VERSION"

# A time unit's answer is local, so the zone matters; Vega's own tests run in this one.
VEGA_ZONE="Europe/Amsterdam"

VEGA_PACKAGES=(
  vega-transforms vega-time vega-scenegraph vega-expression vega-statistics vega-encode
  vega-scale vega-functions vega-crossfilter vega-event-selector vega-format vega-geo
  vega-regression vega-hierarchy vega-voronoi vega-force
)

# One package per process: Vega numbers tuples from a module-level counter, and those ids reach the
# recorded data, so two packages in one process make the second depend on the first.
cd "$NODE_DIR"
echo "==> Recording vega packages"
for package in "${VEGA_PACKAGES[@]}"; do
  TZ="$VEGA_ZONE" node record-upstream-tests.mjs "$CLONES/vega" "$package"
done

# Most of the arithmetic the engine ports is d3's. Each d3 package is its own repository tagged
# `v<version>`; its tests are mocha. The timezone comes from the package's own test script
# (`TZ=America/Los_Angeles mocha ...`).
D3_PACKAGES=(
  d3-array d3-time d3-time-format d3-format d3-dsv d3-geo d3-color d3-shape d3-scale
  d3-interpolate d3-path d3-hierarchy d3-ease d3-scale-chromatic
)

echo "==> Recording d3 packages"
for package in "${D3_PACKAGES[@]}"; do
  version="$(node -p "require('$NODE_DIR/node_modules/$package/package.json').version" 2>/dev/null || true)"
  if [ -z "$version" ]; then
    echo "    $package is not installed; skipping"
    continue
  fi
  clone="$CLONES/$package"
  if ! clone_tag "$clone" "https://github.com/d3/$package.git" "v$version"; then
    echo "    $package: no tag v$version upstream; skipping"
    continue
  fi
  zone="$(node -p "((require('$clone/package.json').scripts||{}).test||'').match(/TZ=([\w\/]+)/)?.[1] || '$VEGA_ZONE'")"
  TZ="$zone" node record-upstream-tests.mjs "$clone" "$package"
done

# An empty file would claim a package was covered when nothing was recorded from it.
for file in "$OUT"/*.json; do
  count="$(node -p "JSON.parse(require('fs').readFileSync('$file','utf8')).calls.length")"
  if [ "$count" = "0" ]; then
    rm "$file"
    echo "    removed $(basename "$file") (recorded nothing)"
  fi
done
echo "==> recorded: $(ls "$OUT" | wc -l | tr -d ' ') packages in $OUT"
